# Generated by Django 4.0.5 on 2024-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='isSocial',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
