# Generated by Django 4.1.13 on 2024-07-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiwriteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_diary_id", models.CharField(max_length=255, unique=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("diarytitle", models.CharField(default="제목", max_length=100)),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("null", "없음"),
                            ("Happiness", "행복"),
                            ("Sadness", "슬픔"),
                            ("Anger", "화남"),
                            ("Annoyance", "짜증"),
                            ("Joy", "기쁨"),
                            ("Fear", "두려움 "),
                            ("Relief", "안도 "),
                            ("Anxiety", "불안  "),
                        ],
                        max_length=100,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("place", models.CharField(default="Unknown", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withfriend", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(max_length=255, unique=True)),
                ("image_file", models.TextField()),
                ("is_representative", models.BooleanField(default=False)),
                (
                    "diary",
                    models.ManyToManyField(
                        related_name="diary_images", to="diaryapp.aiwritemodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aiwritemodel",
            name="images",
            field=models.ManyToManyField(
                related_name="aiwrite_models", to="diaryapp.imagemodel"
            ),
        ),
        migrations.AddField(
            model_name="aiwritemodel",
            name="representative_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaryapp.imagemodel",
            ),
        ),
    ]
