# Generated by Django 4.1.13 on 2024-07-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiwritemodel",
            name="emotion",
            field=models.CharField(
                choices=[
                    ("null", "없음"),
                    ("Happiness", "행복"),
                    ("Joy", "기쁨"),
                    ("Fun", "즐거움 "),
                    ("Relief", "안도 "),
                    ("Excitement", "신남"),
                    ("Sadness", "슬픔"),
                    ("Anger", "화남"),
                    ("Annoyance", "짜증"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="DiaryPlanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_diary_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diaryapp.aiwritemodel",
                    ),
                ),
            ],
        ),
    ]
