# Generated by Django 4.1.13 on 2024-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_commentmodel_diary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
