# Generated by Django 4.1.13 on 2024-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0004_commentmodel_diary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiwritemodel",
            name="diarytitle",
            field=models.CharField(default="역사여행", max_length=100),
        ),
        migrations.AlterField(
            model_name="aiwritemodel",
            name="place",
            field=models.CharField(default="남한산성", max_length=100),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="comment",
            field=models.TextField(blank=True, default="댓글이욤", null=True),
        ),
    ]
