# Generated by Django 4.1.13 on 2024-07-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_alter_aiwritemodel_diarytitle_and_more'),
        ('diaryapp', '0005_commandflag_alter_aiwritemodel_diarytitle_and_more'),
    ]

    operations = [
    ]
