# Generated by Django 4.1.13 on 2024-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0006_merge_20240725_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwritemodel',
            name='nickname_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
