# Generated by Django 4.1.13 on 2024-08-01 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0007_aiwritemodel_nickname_id_and_more"),
        ("diaryapp", "0008_diaryplanmodel_destination"),
    ]

    operations = []
