# Generated by Django 4.1.13 on 2024-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0009_merge_20240801_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="nickname_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
