# Generated by Django 4.1.13 on 2024-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0010_commentmodel_nickname_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentmodel",
            name="nickname_id",
        ),
    ]
