# Generated by Django 4.1.13 on 2024-08-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0011_remove_commentmodel_nickname_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiwritemodel",
            name="representative_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="represented_diary",
                to="diaryapp.imagemodel",
            ),
        ),
    ]
