# Generated by Django 4.1.13 on 2024-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0014_remove_aiwritemodel_place_aiwritemodel_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiwritemodel",
            name="place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
