# Generated by Django 4.1.13 on 2024-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0016_wishlist_city_wishlist_province_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="plan_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user_email", "plan_id")},
        ),
    ]
